"""fix

Revision ID: 13deebb12c9d
Revises: d32f50c9f662
Create Date: 2025-04-27 22:19:03.004822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13deebb12c9d'
down_revision: Union[str, None] = 'd32f50c9f662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_id'), 'meal_plans', ['id'], unique=False)
    op.create_table('day_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_plan_id', 'date', name='uq_plan_date')
    )
    op.create_index(op.f('ix_day_schedules_date'), 'day_schedules', ['date'], unique=False)
    op.create_index(op.f('ix_day_schedules_id'), 'day_schedules', ['id'], unique=False)
    op.create_table('day_schedule_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_schedule_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_schedule_id'], ['day_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_schedule_id', 'order', name='uq_day_order')
    )
    op.create_index(op.f('ix_day_schedule_recipes_id'), 'day_schedule_recipes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_schedule_recipes_id'), table_name='day_schedule_recipes')
    op.drop_table('day_schedule_recipes')
    op.drop_index(op.f('ix_day_schedules_id'), table_name='day_schedules')
    op.drop_index(op.f('ix_day_schedules_date'), table_name='day_schedules')
    op.drop_table('day_schedules')
    op.drop_index(op.f('ix_meal_plans_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    # ### end Alembic commands ###
