"""cascade del

Revision ID: 3cd5184f8391
Revises: 663722544b5d
Create Date: 2024-12-01 16:37:24.444994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd5184f8391'
down_revision: Union[str, None] = '663722544b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interval_employee_employee_id_fkey', 'interval_employee', type_='foreignkey')
    op.drop_constraint('interval_employee_interval_id_fkey', 'interval_employee', type_='foreignkey')
    op.create_foreign_key(None, 'interval_employee', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interval_employee', 'visitinterval', ['interval_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interval_employee', type_='foreignkey')
    op.drop_constraint(None, 'interval_employee', type_='foreignkey')
    op.create_foreign_key('interval_employee_interval_id_fkey', 'interval_employee', 'visitinterval', ['interval_id'], ['id'])
    op.create_foreign_key('interval_employee_employee_id_fkey', 'interval_employee', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###
