"""Add visit_intervals relationship to Employee

Revision ID: 590ef27ff540
Revises: a27e77b24c3a
Create Date: 2024-11-17 15:48:56.199341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590ef27ff540'
down_revision: Union[str, None] = 'a27e77b24c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
