"""delete unique constr

Revision ID: 63f5b3fab87f
Revises: 13deebb12c9d
Create Date: 2025-04-27 23:04:20.364735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f5b3fab87f'
down_revision: Union[str, None] = '13deebb12c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_plan_date', 'day_schedules', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_plan_date', 'day_schedules', ['meal_plan_id', 'date'])
    # ### end Alembic commands ###
