"""add first spot time

Revision ID: 663722544b5d
Revises: 0eaa48d7f292
Create Date: 2024-12-01 15:00:36.964729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '663722544b5d'
down_revision: Union[str, None] = '0eaa48d7f292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval_employee', sa.Column('first_spot_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interval_employee', 'first_spot_datetime')
    # ### end Alembic commands ###
