"""Last one)

Revision ID: 7ea0e9bf9593
Revises: 9f8a5990eade
Create Date: 2024-11-18 11:10:30.326477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea0e9bf9593'
down_revision: Union[str, None] = '9f8a5990eade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval_employee', sa.Column('photo', sa.String(), nullable=True))
    op.drop_column('interval_employee', 'max_unregistered_photo')
    op.drop_column('interval_employee', 'max_unregistered')
    op.add_column('visitinterval', sa.Column('max_unregistered', sa.Integer(), nullable=True))
    op.add_column('visitinterval', sa.Column('max_unregistered_photo', sa.String(), nullable=True))
    op.drop_column('visitinterval', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitinterval', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('visitinterval', 'max_unregistered_photo')
    op.drop_column('visitinterval', 'max_unregistered')
    op.add_column('interval_employee', sa.Column('max_unregistered', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interval_employee', sa.Column('max_unregistered_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('interval_employee', 'photo')
    # ### end Alembic commands ###
