"""Fix

Revision ID: 7fb3e01bebc5
Revises: 590ef27ff540
Create Date: 2024-11-18 10:54:41.255347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb3e01bebc5'
down_revision: Union[str, None] = '590ef27ff540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval_employee', sa.Column('max_unregistered_photo', sa.String(), nullable=True))
    op.drop_column('interval_employee', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval_employee', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('interval_employee', 'max_unregistered_photo')
    # ### end Alembic commands ###
