"""Fixation

Revision ID: 9f8a5990eade
Revises: 7fb3e01bebc5
Create Date: 2024-11-18 11:04:25.745482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8a5990eade'
down_revision: Union[str, None] = '7fb3e01bebc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval_employee', sa.Column('max_unregistered', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interval_employee', 'max_unregistered')
    # ### end Alembic commands ###
