"""refactor bd add intervals

Revision ID: a27e77b24c3a
Revises: 090093ed29a2
Create Date: 2024-11-17 12:33:16.098313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a27e77b24c3a'
down_revision: Union[str, None] = '090093ed29a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitinterval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitinterval_id'), 'visitinterval', ['id'], unique=False)
    op.create_table('interval_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('interval_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['interval_id'], ['visitinterval.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interval_employee_id'), 'interval_employee', ['id'], unique=False)
    op.drop_index('ix_visits_id', table_name='visits')
    op.drop_table('visits')
    op.add_column('events', sa.Column('video', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'video')
    op.create_table('visits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('visit_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='visits_employee_id_fkey'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='visits_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='visits_pkey')
    )
    op.create_index('ix_visits_id', 'visits', ['id'], unique=False)
    op.drop_index(op.f('ix_interval_employee_id'), table_name='interval_employee')
    op.drop_table('interval_employee')
    op.drop_index(op.f('ix_visitinterval_id'), table_name='visitinterval')
    op.drop_table('visitinterval')
    # ### end Alembic commands ###
