"""Add servings

Revision ID: ed91841acf9d
Revises: 690057353202
Create Date: 2025-05-07 11:57:08.300266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed91841acf9d'
down_revision: Union[str, None] = '690057353202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('servings', sa.Integer(), nullable=False,server_default=sa.text('1'),))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'servings')
    # ### end Alembic commands ###
