version: '3.8'

networks:
  network:
    driver: bridge

services:
  fastapi:
    image: a1exdocker/uirs-back:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - /src/media:/app/media
    environment:
      - APP_ENV=prod
      - DB_URL=postgresql+asyncpg://uirs-user:VuILDIB3@db:5432/uirs
    networks:
      - network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: uirs-user
      POSTGRES_PASSWORD: VuILDIB3
      POSTGRES_DB: uirs
    ports:
      - "1337:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - network

volumes:
  postgres_db:
