version: '3.8'

services:
  fastapi:
    image: x1sty/mdp-back:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - /src/media:/app/media
    environment:
      - APP_ENV=prod
      - DB_URL=postgresql+asyncpg://mdp-user:VuILDIB3@db:5432/mdp

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: mdp-user
      POSTGRES_PASSWORD: VuILDIB3
      POSTGRES_DB: mdp
    ports:
      - "1337:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
