- name: Помидоры
  icon_url: null
- name: Огурцы
  icon_url: null
- name: Баклажаны
  icon_url: null
- name: Кабачки
  icon_url: null
- name: Патиссоны
  icon_url: null
- name: Перец
  icon_url: null
- name: Картофель
  icon_url: null
- name: Морковь
  icon_url: null
- name: Лук
  icon_url: null
- name: Чеснок
  icon_url: null
- name: Редис
  icon_url: null
- name: Свекла
  icon_url: null
- name: Капуста
  icon_url: null
- name: Брокколи
  icon_url: null
- name: Цветная капуста
  icon_url: null
- name: Брюссельская капуста
  icon_url: null
- name: Пекинская капуста
  icon_url: null
- name: Салат айсберг
  icon_url: null
- name: Шпинат
  icon_url: null
- name: Щавель
  icon_url: null
- name: Кукуруза
  icon_url: null
- name: Фасоль
  icon_url: null
- name: Горох
  icon_url: null
- name: Нут
  icon_url: null
- name: Чечевица
  icon_url: null
- name: Соя
  icon_url: null
- name: Спаржа
  icon_url: null
- name: Спаржевая фасоль
  icon_url: null
- name: Шампиньоны
  icon_url: null
- name: Лисички
  icon_url: null
- name: Белые
  icon_url: null
- name: Вешенки
  icon_url: null
- name: Маслята
  icon_url: null
- name: Опята
  icon_url: null
- name: Абрикос
  icon_url: null
- name: Персик
  icon_url: null
- name: Слива
  icon_url: null
- name: Груша
  icon_url: null
- name: Яблоко
  icon_url: null
- name: Виноград
  icon_url: null
- name: Арбуз
  icon_url: null
- name: Дыня
  icon_url: null
- name: Клубника
  icon_url: null
- name: Малина
  icon_url: null
- name: Черника
  icon_url: null
- name: Голубика
  icon_url: null
- name: Крыжовник
  icon_url: null
- name: Смородина
  icon_url: null
- name: Ежевика
  icon_url: null
- name: Вишня
  icon_url: null
- name: Черешня
  icon_url: null
- name: Лимон
  icon_url: null
- name: Лайм
  icon_url: null
- name: Киви
  icon_url: null
- name: Манго
  icon_url: null
- name: Гранат
  icon_url: null
- name: Инжир
  icon_url: null
- name: Финики
  icon_url: null
- name: Хурма
  icon_url: null
- name: Личи
  icon_url: null
- name: Ананас
  icon_url: null
- name: Кокос
  icon_url: null
- name: Мандарин
  icon_url: null
- name: Грейпфрут
  icon_url: null
- name: Помело
  icon_url: null
- name: Папайя
  icon_url: null
- name: Апельсин
  icon_url: null
- name: Банан
  icon_url: null
- name: Авокадо
  icon_url: null
- name: Мёд
  icon_url: null
- name: Сахар
  icon_url: null
- name: Соль
  icon_url: null
- name: Чёрный перец
  icon_url: null
- name: Красный перец
  icon_url: null
- name: Корица
  icon_url: null
- name: Куркума
  icon_url: null
- name: Имбирь
  icon_url: null
- name: Ванилин
  icon_url: null
- name: Разрыхлитель
  icon_url: null
- name: Дрожжи
  icon_url: null
- name: Сода
  icon_url: null
- name: Горчица
  icon_url: null
- name: Кетчуп
  icon_url: null
- name: Майонез
  icon_url: null
- name: Соевый соус
  icon_url: null
- name: Рыбный соус
  icon_url: null
- name: Табаско
  icon_url: null
- name: Горчица дижонская
  icon_url: null
- name: Масло подсолнечное
  icon_url: null
- name: Масло оливковое
  icon_url: null
- name: Масло сливочное
  icon_url: null
- name: Кунжутное масло
  icon_url: null
- name: Молоко
  icon_url: null
- name: Кефир
  icon_url: null
- name: Йогурт
  icon_url: null
- name: Сливки
  icon_url: null
- name: Сметана
  icon_url: null
- name: Сыр
  icon_url: null
- name: Творог
  icon_url: null
- name: Мука
  icon_url: null
- name: Рис
  icon_url: null
- name: Гречка
  icon_url: null
- name: Булгур
  icon_url: null
- name: Кускус
  icon_url: null
- name: Перловка
  icon_url: null
- name: Овсянка
  icon_url: null
- name: Манка
  icon_url: null
- name: Пшено
  icon_url: null
- name: Ячневая крупа
  icon_url: null
- name: Макароны
  icon_url: null
- name: Спагетти
  icon_url: null
- name: Вермишель
  icon_url: null
- name: Баранина
  icon_url: null
- name: Говядина
  icon_url: null
- name: Свинина
  icon_url: null
- name: Телятина
  icon_url: null
- name: Курица
  icon_url: null
- name: Индейка
  icon_url: null
- name: Утка
  icon_url: null
- name: Перепела
  icon_url: null
- name: Яйца
  icon_url: static/ingredients/Яйца.png
- name: Креветки
  icon_url: null
- name: Кальмары
  icon_url: null
- name: Осьминоги
  icon_url: null
- name: Треска
  icon_url: null
- name: Сёмга
  icon_url: null
- name: Горбуша
  icon_url: null
- name: Скумбрия
  icon_url: null
- name: Тунец
  icon_url: null
